// Real Chromium touch input, using the Electron dependency already in the app.
// Run with: npx electron tests/chartTouch.cjs
const { app, BrowserWindow } = require('electron')
const assert = require('node:assert/strict')
const path = require('node:path')
const fs = require('node:fs')
let server, win
const delay = ms => new Promise(resolve => setTimeout(resolve, ms))
async function main() {
  const { createServer } = await import('vite')
  const { default: react } = await import('@vitejs/plugin-react')
  const root = path.resolve(__dirname, '..')
  server = await createServer({ configFile: false, root: path.join(__dirname, 'fixtures'), plugins: [react()], server: { host: '127.0.0.1', port: 0, fs: { allow: [root] } } })
  await server.listen()
  win = new BrowserWindow({ width: 390, height: 844, show: false, webPreferences: { backgroundThrottling: false } })
  const errors = []
  win.webContents.on('console-message', (_event, level, message) => { if (level >= 3 && !message.includes('Content Security Policy')) errors.push(message) })
  win.webContents.debugger.attach('1.3')
  const cdp = (method, params) => win.webContents.debugger.sendCommand(method, params)
  await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 2, mobile: true })
  await cdp('Emulation.setTouchEmulationEnabled', { enabled: true, maxTouchPoints: 5 })
  await win.loadURL(`${server.resolvedUrls.local[0]}charts.html`)
  const js = code => win.webContents.executeJavaScript(code)
  for (let i = 0; i < 100 && !(await js('!!document.querySelector("canvas")')); i++) await delay(50)
  assert.equal(await js('document.querySelectorAll("canvas").length'), 5, errors.join('\n'))
  const click = async label => { await js(`document.querySelector('[aria-label="${label}"]').click()`); await delay(100) }
  const rect = async selector => js(`(() => { const r = document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect(); return { x: r.x, y: r.y, width: r.width, height: r.height } })()`)
  const touch = async (type, points = []) => { await cdp('Input.dispatchTouchEvent', { type, touchPoints: points.map(([id, x, y]) => ({ id, x, y, radiusX: 4, radiusY: 4 })) }); await delay(35) }
  const tap = async (x, y) => { await touch('touchStart', [[1, x, y]]); await touch('touchEnd') }
  let r = await rect('canvas')
  await tap(r.x + r.width / 2, r.y + 100)
  assert.match(await js('document.querySelector(".chart-tooltip").textContent'), /mph/)
  assert.equal(await js('getComputedStyle(document.querySelector("canvas")).touchAction'), 'pan-y pinch-zoom')
  await touch('touchStart', [[1, r.x + 150, r.y + 180]])
  await touch('touchMove', [[1, r.x + 150, r.y + 80]])
  await touch('touchEnd')
  assert.ok(await js('document.querySelector("main").scrollTop > 0'), 'embedded charts allow page scrolling')
  await click('Maximize SPEED')
  assert.equal(await js('document.querySelectorAll("dialog:modal").length'), 1)
  assert.equal(await js('document.activeElement.getAttribute("aria-label")'), 'Close SPEED full screen')
  assert.equal(await js('getComputedStyle(document.querySelector("dialog canvas")).touchAction'), 'none')
  r = await rect('dialog[open] canvas')
  assert.ok(r.height > 500 && r.width <= 390, JSON.stringify(r))
  const canvas = 'document.querySelector("dialog[open] canvas")'
  const inspectAt = async fraction => { await delay(310); await tap(r.x + 50 + (r.width - 66) * fraction, r.y + r.height / 2); return js('window.hoverX') }
  const before = await inspectAt(0.25)
  const y = r.y + r.height / 2
  await touch('touchStart', [[1, r.x + 140, y], [2, r.x + 240, y]])
  await touch('touchMove', [[1, r.x + 90, y], [2, r.x + 290, y]])
  await touch('touchEnd')
  const after = await inspectAt(0.25)
  assert.ok(after > before + 70, `pinch zoom changed visible distance: ${before} → ${after}`)
  await touch('touchStart', [[1, r.x + 140, y], [2, r.x + 240, y]])
  await touch('touchMove', [[1, r.x + 170, y], [2, r.x + 270, y]])
  await touch('touchEnd')
  const panned = await inspectAt(0.25)
  assert.ok(panned < after - 20, 'two-finger pan moves the distance window')
  // A canceled pinch cannot leave inspection stuck in gesture mode.
  await touch('touchStart', [[1, r.x + 140, y], [2, r.x + 240, y]])
  await touch('touchCancel')
  assert.ok(Number.isFinite(await inspectAt(0.5)))
  await click('Close SPEED full screen')
  assert.equal(await js('document.activeElement.getAttribute("aria-label")'), 'Maximize SPEED')
  await click('Maximize SPEED')
  r = await rect('dialog[open] canvas')
  assert.ok(Math.abs(await inspectAt(0.25) - panned) < 3, 'view survives close and reopen')
  await tap(r.x + 190, r.y + 120)
  await tap(r.x + 190, r.y + 120)
  assert.ok(Math.abs(await inspectAt(0.25) - before) < 3, 'double tap resets zoom')
  await cdp('Emulation.setDeviceMetricsOverride', { width: 844, height: 390, deviceScaleFactor: 2, mobile: true })
  await delay(100)
  r = await rect('dialog[open] canvas')
  assert.ok(r.width > 750 && r.height > 100 && r.y + r.height <= 390, JSON.stringify(r))
  await cdp('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 })
  await delay(100)
  assert.equal(await js('document.querySelectorAll("dialog[open]").length'), 0)
  await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 2, mobile: true })
  await click('Maximize G-G')
  r = await rect('dialog[open] canvas')
  const imageBefore = await js(`${canvas}.toDataURL()`)
  await touch('touchStart', [[1, 140, 350], [2, 240, 350]])
  await touch('touchMove', [[1, 90, 350], [2, 290, 350]])
  await touch('touchEnd')
  assert.notEqual(await js(`${canvas}.toDataURL()`), imageBefore, 'G-G plot redraws after pinch')
  await click('Close G-G full screen')
  for (const title of ['CORNER STATS', 'BRAKING', 'CONSISTENCY']) {
    await click(`Maximize ${title}`)
    r = await rect('dialog[open] canvas')
    await tap(r.x + 180, r.y + (r.height + 12) / 2)
    assert.match(await js('document.querySelector("dialog[open] .chart-tooltip").textContent'), /T1/)
    await click(`Close ${title} full screen`)
  }
  await click('Maximize SEGMENT Δ')
  await js('document.querySelectorAll("dialog[open] .heatmap-cell")[1].click()')
  assert.match(await js('document.querySelector("dialog[open] .heatmap-readout").textContent'), /Lap 1 · S2: 26.2/)
  await click('Close SEGMENT Δ full screen')
  await click('Maximize Track map')
  const svg = 'document.querySelector("dialog[open] .track-map > svg")'
  const original = await js(`${svg}.getAttribute('viewBox')`)
  await touch('touchStart', [[1, 140, 350], [2, 240, 350]])
  await touch('touchMove', [[1, 90, 350], [2, 290, 350]])
  await touch('touchEnd')
  assert.ok(Number((await js(`${svg}.getAttribute('viewBox')`)).split(' ')[2]) < Number(original.split(' ')[2]), 'map pinches in world coordinates')
  await click('Close Track map full screen')
  assert.deepEqual(errors, [])
  if (process.env.CHART_SCREENSHOT) {
    await click('Maximize SPEED')
    fs.writeFileSync(process.env.CHART_SCREENSHOT, (await win.webContents.capturePage()).toPNG())
  }
  console.log('PASS: mobile scrolling, pinned readouts, fullscreen/focus, pinch, pan, cancellation, reset, state preservation, rotation, G-G, corner charts, heatmap and map')
}
app.whenReady().then(main).then(async () => { await server?.close(); app.exit(0) }).catch(async error => { console.error(error); await server?.close(); app.exit(1) })
